name: Annotation Commands test

on:
  push:
    branches:
      - test/annotation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  AddAnnotation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'

      - name: Annotate code linting results
        run: |
          sleep 120
          node js/src/print-annotation.js
